"""Solutions catalog data for paper2skills Playbook."""
from __future__ import annotations
from typing import Any


SOLUTIONS_CATALOG = [
    {
        "id": "sol-counterfactual-pricing",
        "title": "反事实推演 → 动态定价架构",
        "subtitle": "因果推断、博弈论与多智能体的融合决策系统",
        "category": "定价策略 AI",
        "tags": ["因果推断", "多智能体", "动态定价", "反直觉决策"],
        "icon": "CP",
        "icon_color": "#8b5cf6",
        "status": "published",
        "updated": "2026-06-20",
        "summary": "打破基于滞后规则的竞价内卷，引入因果推断的反事实基线计算真实利润 Uplift。结合 MAS 跨部门利益制衡，构建反直觉的高价值商业化定价产品。",
        "roi_headline": "告别无效价格战，通过反事实预判提升净利润率 15%-40%",
        "phases": [
            {"name": "Phase 1 因果基线", "duration": "1-2 月", "action": "计算历史真实 Uplift", "roi": "减少盲目降价"},
            {"name": "Phase 2 旁路博弈", "duration": "3-4 月", "action": "MAS Agent 辩论报告", "roi": "决策视角升维"},
            {"name": "Phase 3 闭环门控", "duration": "5-6 月", "action": "自动化调价与风险阻断", "roi": "极致响应"},
        ],
        "layers": [
            {"no": "L1", "name": "信号解析层", "desc": "正交数据获取：海关提单、社媒发帖加速度"},
            {"no": "L2", "name": "因果推演层", "desc": "Do-Calculus 反事实基线，测算净增量"},
            {"no": "L3", "name": "董事会博弈层", "desc": "流量、供应链、财务 Agent 纳什均衡"},
            {"no": "L4", "name": "门控执行层", "desc": "三轨合规验证与 API 自动化执行"}
        ],
        "core_skills": [
            "Skill-Cross-Domain-Orthogonal-Signals",
            "Skill-Counterfactual-Price-Elasticity",
            "Skill-Uplift-Cannibalization-Modeling",
            "Skill-Stackelberg-Equilibrium-Competitive-Pricing",
            "Skill-Real-Options-Product-Launch-Timing",
            "Skill-Elasticity-Based-Repricing-Gate",
            "Skill-CVaR-Inventory-Risk-Portfolio",
            "Skill-Nash-Equilibrium-Pricing-Model",
            "Skill-Anchoring-Effect-Pricing-Optimization",
            "Skill-Channel-Budget-Reallocation-Trigger",
        ],
        "traps": [],
    },
    {
        "id": "sol-sc-tag-to-decision",
        "title": "供应链标签工程 → 决策全链路架构",
        "subtitle": "从 Palantir 本体论到母婴跨境电商可执行方案",
        "category": "供应链 AI",
        "tags": ["供应链", "标签工程", "Palantir", "决策自动化", "MCP"],
        "icon": "SC",
        "icon_color": "#0ea5e9",
        "status": "published",
        "updated": "2026-06-18",
        "summary": "基于 Palantir 本体论四层架构，设计七层供应链 AI 决策系统。标签工程作为语义枢纽，打通从原始数据到自动执行决策的完整链路。含三大架构陷阱、分阶段实施路线图（MVP→12个月）、71个核心 Skill 索引。",
        "roi_headline": "运营团队供应链日常工作减少 60%，异常响应从小时级→分钟级",
        "phases": [
            {"name": "Phase 0 地基", "duration": "1-4 周", "action": "SKU ID 统一 + 供应商本体", "roi": "必须投入，不可跳过"},
            {"name": "Phase 1 MVP", "duration": "5-12 周", "action": "库存健康标签 + 补货自动触发", "roi": "补货延误 ↓30%"},
            {"name": "Phase 2 扩展", "duration": "3-6 月", "action": "ML预测标签 + 因果分析 + Agent", "roi": "决策准确率 ↑40%"},
            {"name": "Phase 3 智能化", "duration": "6-12 月", "action": "全自动 Action + 闭环学习", "roi": "运营工时 ↓60%"},
        ],
        "layers": [
            {"no": "L1", "name": "数据基础层", "desc": "Golden Record · OKB Graph · Feature Store · Event Sourcing"},
            {"no": "L2", "name": "本体语义层", "desc": "ObjectTypes · LinkTypes · LLM自动构建 · Schema版本化"},
            {"no": "L3", "name": "标签工程层", "desc": "静态标签 · 动态标签 · 预测标签 · 规则→ML→LLM→图传播"},
            {"no": "L4", "name": "信号分析层", "desc": "KPI监控 · 因果DAG根因归因 · GCF隐性需求 · 置信区间"},
            {"no": "L5", "name": "决策推理层", "desc": "What-if多情景 · MILP多目标规划 · 因果干预 · 置信门控"},
            {"no": "L6", "name": "行动执行层", "desc": "全自动/半自动/人审三档 · MCP写回ERP/WMS · 多智能体共识"},
            {"no": "L7", "name": "反馈学习层", "desc": "数字孪生 · 审计追踪 · 决策结果闭环标签更新"},
        ],
        "traps": [
            {"no": "①", "title": "跳过实体 ID 统一直接上 ML", "desc": "ERP/FBA/供应商三套编码不统一，所有分析建在沙上。Phase 2 强制补做，额外 3-6 个月。"},
            {"no": "②", "title": "标签设计成「结论」而非「信号」", "desc": "`needs_replenishment` 是决策输出不是输入。标签只存储可测量事实状态，决策逻辑在 L5 动态计算。"},
            {"no": "③", "title": "Action 全自动化没有置信度门控", "desc": "置信度 55% 和 95% 的决策同等自动执行，一个错误 PO 锁定 10-50 万元资金。必须三档执行。"},
        ],
        "core_skills": [
            "Skill-Graph-OKB-Design-SC", "Skill-Ontology-LLM-AutoBuild-SC",
            "Skill-Tag-Schema-Engineering-Lifecycle", "Skill-Auto-Tagging-Pipeline-Rule-ML-LLM",
            "Skill-Tag-Propagation-Supply-Chain", "Skill-SC-Causal-DAG-E2E-Attribution",
            "Skill-GCF-Counterfactual-Unobserved-Demand", "Skill-SC-WhatIf-Scenario-Analysis-Engine",
            "Skill-Supply-Chain-Ontology-Action-Trigger", "Skill-LLM-SC-MultiAgent-Consensus-Replenishment",
            "Skill-SC-Agent-MCP-ERP-Integration", "Skill-SCPA-Autonomous-SC-Planning-Agent",
            "Skill-SC-Digital-Twin-Sync-Architecture", "Skill-Decision-Confidence-Calibration-SC",
        ],
        "vault_doc": "07-资源库/SC-TagToDecision-Architecture.md",
    },
    {
        "id": "sol-aigc-content-factory",
        "title": "AIGC 内容工厂 → 全渠道投放自动化",
        "subtitle": "从商品图文生成到多平台 A/B 测试投放的完整闭环",
        "category": "AI 内容 & 营销",
        "tags": ["AIGC", "内容生成", "A/B测试", "多渠道投放", "TikTok"],
        "icon": "AI",
        "icon_color": "#7c3aed",
        "status": "published",
        "updated": "2026-06-18",
        "summary": "构建母婴跨境卖家的 AI 内容生产线：商品主图质量门控 → 多语言 Listing 生成 → A+ Content 自动排版 → 短视频素材制作 → 多平台 A/B 测试 → 投放预算自动分配。将内容制作周期从 2 周压缩至 2 天，单 SKU 内容成本降低 70%。",
        "roi_headline": "内容制作周期 2周→2天，单 SKU 内容成本降低 70%，CTR 提升 15-25%",
        "phases": [
            {"name": "Phase 0 素材采集", "duration": "1-2 周", "action": "商品原始图/视频采集 + 品牌调性提取", "roi": "建立内容生产基准"},
            {"name": "Phase 1 内容生成", "duration": "3-6 周", "action": "主图质量评分 + 多语言 Listing + A+ 模板生成", "roi": "内容成本 ↓50%"},
            {"name": "Phase 2 测试优化", "duration": "2-4 月", "action": "多臂老虎机 A/B 测试 + CTR/CVR 追踪", "roi": "CTR 提升 15-25%"},
            {"name": "Phase 3 全自动化", "duration": "4-8 月", "action": "内容生成 → 测试 → 胜出版本自动投放", "roi": "运营人力 ↓60%"},
        ],
        "layers": [
            {"no": "L1", "name": "素材基础层", "desc": "商品白底图 · 品牌色板 · 语调档案 · 竞品参考图"},
            {"no": "L2", "name": "内容生成层", "desc": "主图质量评分 · Stable Diffusion 场景化 · 多语言 Listing LLM · A+ 模板引擎"},
            {"no": "L3", "name": "内容审核层", "desc": "合规词检测 · 品牌一致性检查 · 文化本地化审核"},
            {"no": "L4", "name": "测试分发层", "desc": "多臂老虎机 A/B · 各平台规格适配 · 流量分配策略"},
            {"no": "L5", "name": "归因分析层", "desc": "素材 → 点击 → 转化归因 · 内容特征 XGBoost 归因"},
            {"no": "L6", "name": "闭环学习层", "desc": "胜出素材特征提炼 → 下一批生成参数更新"},
        ],
        "traps": [
            {"no": "①", "title": "先生成再合规审查", "desc": "AI 生成的内容含 'clinically tested' 等违禁词，上架后被 Amazon 下架或 FTC 罚款。必须在生成阶段嵌入合规过滤器。"},
            {"no": "②", "title": "用同一套素材跨平台", "desc": "Amazon 主图要求白底、TikTok 要竖版短视频、Shopee 要本地化场景图。平台规格不匹配导致流量损失 30%+。"},
            {"no": "③", "title": "A/B 测试样本量不足就结论", "desc": "在统计显著性不足时停止测试，伪胜出版本实际 CTR 与对照组无差异。必须预设功效分析和最小样本量。"},
        ],
        "core_skills": [
            "Skill-Product-Image-Quality-Assessment", "Skill-Product-Background-Scene-Generation",
            "Skill-Multilingual-Listing-Generation", "Skill-A-Plus-Content-Template-Engine",
            "Skill-Cross-Market-Content-Localization", "Skill-Short-Video-Commerce-Attribution",
            "Skill-Email-Sequence-RL-Optimizer", "Skill-TikTok-Shop-Content-Commerce-Funnel",
            "Skill-Multi-Platform-Ad-Budget-Allocator", "Skill-KOL-ROI-Causal-Attribution",
            "Skill-Category-Compliance-Prescan", "Skill-Listing-Compliance-Auto-Repair",
        ],
    },
    {
        "id": "sol-intelligent-pricing-revenue",
        "title": "智能定价 → 利润最大化全链路",
        "subtitle": "从竞品监控到动态调价再到 P&L 归因的闭环决策系统",
        "category": "定价 & 财务",
        "tags": ["动态定价", "价格弹性", "P&L", "竞品监控", "利润优化"],
        "icon": "$$",
        "icon_color": "#059669",
        "status": "published",
        "updated": "2026-06-18",
        "summary": "构建母婴跨境卖家的智能定价决策系统：竞品价格实时监控 → 价格弹性建模 → 动态调价策略 → 促销效果评估 → P&L 影响归因 → 定价决策闭环。将价格决策从「拍脑袋」升级为「数据驱动」，毛利率提升 3-8 个百分点。",
        "roi_headline": "定价响应速度从 3 天→实时，毛利率提升 3-8 pp，年化增利 $5-20 万",
        "phases": [
            {"name": "Phase 0 数据基础", "duration": "1-3 周", "action": "竞品价格爬取 + 成本结构录入 + 历史订单清洗", "roi": "定价决策有数据支撑"},
            {"name": "Phase 1 弹性建模", "duration": "4-8 周", "action": "价格弹性估计 + 需求曲线拟合 + 竞品响应模型", "roi": "找到利润最优价格点"},
            {"name": "Phase 2 动态调价", "duration": "2-4 月", "action": "规则引擎自动跟价 + 促销日历联动 + 库存价格联动", "roi": "毛利率 ↑3-5pp"},
            {"name": "Phase 3 P&L 闭环", "duration": "4-8 月", "action": "定价决策 → P&L 影响归因 → 定价策略自我修正", "roi": "年化毛利增量 $5-20 万"},
        ],
        "layers": [
            {"no": "L1", "name": "数据采集层", "desc": "竞品价格实时爬取 · 促销活动监控 · 平台费率变化追踪"},
            {"no": "L2", "name": "需求建模层", "desc": "价格弹性回归 · 交叉弹性 · 季节性分解 · 节假日调整"},
            {"no": "L3", "name": "竞争分析层", "desc": "竞品定价策略识别 · 跟价 vs 领价决策 · 品牌定价护城河"},
            {"no": "L4", "name": "调价执行层", "desc": "规则引擎（floor/ceiling）· Repricing API · 促销协同"},
            {"no": "L5", "name": "财务归因层", "desc": "定价 → 毛利归因 · P&L 仿真 · 现金流影响预测"},
            {"no": "L6", "name": "策略优化层", "desc": "多目标优化（利润/份额/清仓）· 竞品博弈策略"},
        ],
        "traps": [
            {"no": "①", "title": "只看竞品最低价跟价", "desc": "最低价策略在非弹性品类会引发价格战，同时压缩自身利润率。必须先测定品类价格弹性，弹性 < 1 的品类不应激进跟价。"},
            {"no": "②", "title": "调价不考虑库存水位", "desc": "高库存时降价清仓 + 低库存时涨价保利润，两者必须联动。割裂运营导致滞销品越降越贱、爆款越涨越缺货。"},
            {"no": "③", "title": "促销期间不保护锚点价", "desc": "频繁打折让用户的心理锚点价格永久降低，恢复原价后转化率暴跌。促销节奏和力度必须用 DiD 归因管控。"},
        ],
        "core_skills": [
            "Skill-Competitive-Price-Monitoring", "Skill-Price-Elasticity-Estimation",
            "Skill-Dynamic-Pricing-Elasticity", "Skill-Real-Time-Competitive-Repricing",
            "Skill-Causal-RL-Dynamic-Pricing", "Skill-Markdown-Optimization",
            "Skill-Bundle-Pricing-Strategy", "Skill-Cross-Border-Price-Harmonization",
            "Skill-PL-Attribution-Analysis", "Skill-FBA-Cost-Forecast-Adjustment",
            "Skill-Forecast-to-PL-Bridge", "Skill-Promotion-Effectiveness",
        ],
    },
    {
        "id": "sol-global-compliance-firewall",
        "title": "全球合规防火墙 → 风险零容忍运营体系",
        "subtitle": "从 Listing 预扫描到账号健康管理的自动化合规全链路",
        "category": "合规 & 风控",
        "tags": ["合规", "风控", "账号健康", "产品安全", "平台规则"],
        "icon": "CC",
        "icon_color": "#dc2626",
        "status": "published",
        "updated": "2026-06-18",
        "summary": "构建母婴跨境卖家的合规防火墙：新品上架前合规预扫描 → Listing 违规词自动修复 → 竞品投诉监控 → 账号健康实时预警 → 申诉 SOP 自动生成。将合规响应从「事后救火」转变为「事前预防」，封号风险降低 80%。",
        "roi_headline": "违规 Listing 拦截率 95%+，封号风险 ↓80%，合规处理时间 3天→4小时",
        "phases": [
            {"name": "Phase 0 合规基线", "duration": "1-2 周", "action": "现有 Listing 全量合规扫描 + 问题分级", "roi": "摸清风险存量"},
            {"name": "Phase 1 新品门控", "duration": "3-6 周", "action": "上架前合规预扫描 + 证书要求清单 + 禁用词过滤", "roi": "新品违规率 ↓90%"},
            {"name": "Phase 2 动态监控", "duration": "2-4 月", "action": "平台规则变更监控 + 竞品投诉预警 + 账号健康仪表盘", "roi": "违规响应 3天→4小时"},
            {"name": "Phase 3 智能申诉", "duration": "4-8 月", "action": "申诉 POA 自动生成 + 合规护城河构建", "roi": "申诉成功率 ↑35%"},
        ],
        "layers": [
            {"no": "L1", "name": "规则知识库", "desc": "Amazon ToS · FTC 禁用词 · CPSC 产品安全 · 各国 VAT 合规 · 平台规则变更 RSS"},
            {"no": "L2", "name": "内容扫描层", "desc": "Listing 违规词检测 · 图片合规检查 · 医疗宣称识别 · 绝对化用语拦截"},
            {"no": "L3", "name": "产品认证层", "desc": "品类认证路径规划 · 证书有效期追踪 · SGS/BV/TÜV API 对接"},
            {"no": "L4", "name": "账号监控层", "desc": "ODR/LR/VTR 实时追踪 · 异常信号预警 · 竞品恶意投诉识别"},
            {"no": "L5", "name": "风险处置层", "desc": "分级处置 SOP · POA 模板生成 · 申诉文档自动整理"},
            {"no": "L6", "name": "护城河层", "desc": "高门槛认证（CE/FDA 510k）建立竞争壁垒 · 合规知识库沉淀"},
        ],
        "traps": [
            {"no": "①", "title": "只扫 Title 不扫 Bullet/A+ 内容", "desc": "Amazon 合规审查覆盖所有可见文本，包括 A+ Content、视频字幕、Q&A。只扫 Title 导致 70% 的违规漏网。"},
            {"no": "②", "title": "证书到期不追踪", "desc": "SGS/BV 检测报告通常 1-2 年有效期，过期后 Listing 可被投诉下架。必须建立证书到期日历和自动提醒。"},
            {"no": "③", "title": "申诉模板千篇一律", "desc": "Amazon 审核员见过太多模板化 POA，识别率极高。申诉文件必须包含具体的违规修复证据截图和可量化的改进指标。"},
        ],
        "core_skills": [
            "Skill-Category-Compliance-Prescan", "Skill-Listing-Compliance-Auto-Repair",
            "Skill-AI-Product-Safety-Certification", "Skill-CPSC-Children-Product-Safety",
            "Skill-Cross-Border-Compliance-Framework", "Skill-Regulatory-Change-Monitoring",
            "Skill-Regulatory-Graph-Compliance-Monitor", "Skill-Platform-Policy-Change-Adaptive-Monitor",
            "Skill-Account-Health-Proactive-Monitor", "Skill-Amazon-Account-Appeal-Strategy",
            "Skill-Brand-Listing-Hijacking-Detection", "Skill-IP-Trademark-Brand-Monitoring",
            "Skill-VOC-Compliance-Signal-Mining", "Skill-Compliance-Scored-Guardrail-Orchestration",
        ],
    },
    {
        "id": "sol-user-growth-repurchase-flywheel",
        "title": "用户增长 → 复购飞轮全链路",
        "subtitle": "从拉新到激活到留存到裂变的 AI 驱动增长引擎",
        "category": "增长 & 用户运营",
        "tags": ["增长模型", "复购", "LTV", "私域", "用户分析"],
        "icon": "GR",
        "icon_color": "#10b981",
        "status": "published",
        "updated": "2026-06-19",
        "summary": "构建母婴跨境品牌的 AI 增长飞轮：用户分层（RFM）→ 流失预警 → 最佳复购触达时机预测 → 邮件/WhatsApp/积分多通道干预 → 干预效果归因 → 策略自我优化。将用户 LTV 从均值视角升级为个体精准运营，复购率提升 20-35%。",
        "roi_headline": "复购率提升 20-35%，LTV 增长 40%，客户获取成本摊薄 28%",
        "phases": [
            {"name": "Phase 0 数据基础", "duration": "1-2 周", "action": "历史订单清洗 + RFM 分层基线建立", "roi": "用户价值可视化"},
            {"name": "Phase 1 流失预警", "duration": "3-6 周", "action": "流失预测模型上线 + 高危用户告警", "roi": "复购率 ↑8%"},
            {"name": "Phase 2 精准触达", "duration": "2-4 月", "action": "最优触达时机 + 多通道 A/B 优化", "roi": "LTV ↑20%"},
            {"name": "Phase 3 飞轮闭环", "duration": "4-8 月", "action": "会员体系 + 自动化增长引擎 + 裂变机制", "roi": "CAC 摊薄 28%"},
        ],
        "layers": [
            {"no": "L1", "name": "用户数据层", "desc": "订单历史 · 行为事件流 · 跨平台 ID 统一"},
            {"no": "L2", "name": "分层分析层", "desc": "RFM 分群 · Cohort 分析 · 生命周期阶段识别"},
            {"no": "L3", "name": "预测模型层", "desc": "流失概率 · 复购时间窗 · LTV 预测 · 升级倾向"},
            {"no": "L4", "name": "触达策略层", "desc": "个性化内容生成 · 多通道优先级 · 频次控制"},
            {"no": "L5", "name": "归因优化层", "desc": "干预效果 DiD 归因 · Thompson Sampling · 策略演化"},
            {"no": "L6", "name": "飞轮放大层", "desc": "会员积分 ROI · 老带新裂变 · 私域社群运营"},
        ],
        "traps": [
            {"no": "①", "title": "对所有用户发同一套挽回邮件", "desc": "高价值沉睡用户和低价值流失用户需要完全不同的激励策略。同一套模板对高价值用户显得廉价，对低价值用户则浪费成本。必须先做 RFM 分层再差异化干预。"},
            {"no": "②", "title": "复购提醒发得太频繁或太稀疏", "desc": "消耗品类有自然消耗周期（奶粉 30 天，纸尿裤 15 天），在窗口期外发出的提醒打扰用户且转化率极低。必须用生存分析建模个体复购窗口。"},
            {"no": "③", "title": "会员积分设计成「成本中心」", "desc": "积分发放率过高导致积分负债超过复购收益。必须用 DiD 净增量建模在推出积分体系前量化 ROI，设置积分有效期和上限。"},
        ],
        "core_skills": [
            "Skill-RFM-Customer-Segmentation", "Skill-Customer-Churn-Prediction",
            "Skill-Repurchase-Trigger-Timing-Model", "Skill-RFM-to-Action-Policy-Engine",
            "Skill-Email-Sequence-Multiarm-Optimizer", "Skill-WhatsApp-Private-Domain-Analytics",
            "Skill-Loyalty-Program-ROI-Modeling", "Skill-Combo-Customer-Churn-Recovery",
            "Skill-User-Funnel-Analysis", "Skill-Clickstream-Persona-Pipeline",
            "Skill-Tag-Driven-User-Growth-Trigger", "Skill-DiD-Difference-in-Differences",
        ],
    },
    {
        "id": "sol-ai-agent-ops-automation",
        "title": "AI Agent 运营自动化 → 降本增效飞轮",
        "subtitle": "从单点 Agent 工具到多 Agent 协作的电商运营自动化全栈",
        "category": "智能体工程",
        "tags": ["Agent", "MAS", "自动化", "ROI量化", "降本增效"],
        "icon": "AG",
        "icon_color": "#8b5cf6",
        "status": "published",
        "updated": "2026-06-19",
        "summary": "构建母婴跨境卖家的 AI Agent 运营自动化体系：从单个智能 Agent（补货/定价/Listing优化）到多 Agent 协作系统（竞品情报→定价→广告→库存全链路自动化）。提供 Agent ROI 量化框架，帮助决策者评估哪些运营岗位值得 Agent 化、预期回收周期是多少。",
        "roi_headline": "运营人效提升 3-5 倍，重复性运营工作减少 70%，Agent 投资回收期 4-8 个月",
        "phases": [
            {"name": "Phase 0 SOP 梳理", "duration": "1-2 周", "action": "识别高重复度/低判断门槛运营任务，建立 Agent 化优先级矩阵", "roi": "明确 ROI 最高的 Agent 化方向"},
            {"name": "Phase 1 单 Agent 试点", "duration": "3-8 周", "action": "补货 Agent / Listing 优化 Agent 各选一个上线", "roi": "人力节省 40%，错误率 ↓60%"},
            {"name": "Phase 2 多 Agent 协作", "duration": "2-5 月", "action": "竞品情报 + 定价 + 广告 + 库存四 Agent 协同", "roi": "运营效率 ↑200%"},
            {"name": "Phase 3 自我优化", "duration": "5-12 月", "action": "Agent 从历史决策中学习，SOP 自动更新", "roi": "决策质量持续提升"},
        ],
        "layers": [
            {"no": "L1", "name": "SOP 知识层", "desc": "运营 SOP 文档化 · 案例库 · 决策规则树 · 异常处理手册"},
            {"no": "L2", "name": "单 Agent 层", "desc": "补货 Agent · 定价 Agent · Listing 优化 Agent · 客服分诊 Agent"},
            {"no": "L3", "name": "工具调用层", "desc": "SP-API 数据获取 · 广告 API 调整 · 邮件发送 · ERP 写回"},
            {"no": "L4", "name": "多 Agent 编排层", "desc": "Supervisor-Worker 架构 · DAG 执行计划 · 结果汇聚"},
            {"no": "L5", "name": "置信度门控层", "desc": "三档执行（全自动/人工确认/人工接管）· 高风险操作审批"},
            {"no": "L6", "name": "ROI 度量层", "desc": "Agent 成本追踪 · 决策效果归因 · ROI 仪表盘"},
        ],
        "traps": [
            {"no": "①", "title": "直接让 Agent 全自动执行高风险决策", "desc": "未经验证的 Agent 自动提交大额 PO 或大幅调价，一个错误可能造成 $10 万+损失。必须先在沙箱中验证 3 个月，再逐步开放自动化权限。"},
            {"no": "②", "title": "SOP 没有文档化就上 Agent", "desc": "Agent 需要学习人类专家的经验。如果 SOP 只存在于老运营的脑子里，Agent 无法提炼，最终只是随机乱猜。必须先把 SOP 结构化文档化。"},
            {"no": "③", "title": "用 Token 成本评估 Agent ROI", "desc": "LLM Token 费用只是 Agent 总成本的 10-20%，大头是人工审核时间和错误决策成本。ROI 计算必须用「人工节省小时数×时薪 + 错误率降低×平均损失」来计算。"},
        ],
        "core_skills": [
            "Skill-Agent-ROI-Measurement-Framework", "Skill-Agent-Cost-Optimization-Budget-Control",
            "Skill-Agent-Decision-Confidence-Threshold", "Skill-Agent-Workforce-Replacement-Calculator",
            "Skill-MAS-Ecommerce-Ops-Automation", "Skill-MAS-Competitive-Intelligence-Agent",
            "Skill-MAS-Customer-Journey-Orchestration", "Skill-Multi-Agent-Skill-Composition",
            "Skill-Agent-Skill-Runtime-Orchestrator", "Skill-Skill-Card-API-Serving",
            "Skill-Human-in-Loop-Approval-Gate-Tag", "Skill-Agent-Knowledge-Distillation-SOP",
        ],
    },
    {
        "id": "sol-search-traffic-dominance",
        "title": "搜索流量制霸 → 自然流量飞轮",
        "subtitle": "从关键词研究到排名突破再到广告协同的搜索增长全链路",
        "category": "搜索 & 流量",
        "tags": ["搜索排名", "关键词", "SEO", "自然流量", "广告协同"],
        "icon": "SR",
        "icon_color": "#f59e0b",
        "status": "published",
        "updated": "2026-06-19",
        "summary": "构建母婴跨境卖家的搜索流量护城河：关键词蓝海发现 → 排名因子量化 → Listing 语义优化 → 广告飞轮加速 → 自然流量沉淀。搜索排名每提升一个页面，自然流量增长 3-5 倍。将搜索运营从「靠感觉」升级为「数据驱动的流量工程」。",
        "roi_headline": "目标关键词排名从第3页→第1页，自然流量提升3-5倍，广告 ACoS 降低 35%",
        "phases": [
            {"name": "Phase 0 关键词地图", "duration": "1 周", "action": "蓝海关键词挖掘 + 竞争度分析 + 优先级排序", "roi": "找到 ROI 最高的 20 个目标词"},
            {"name": "Phase 1 Listing 优化", "duration": "2-4 周", "action": "语义相关性评分 + Title/Bullet 优化 + A+ Content 升级", "roi": "搜索可见度 ↑40%"},
            {"name": "Phase 2 排名突破", "duration": "2-3 月", "action": "广告加速 + 飞轮效应追踪 + 位置弹性监控", "roi": "核心词排名进入首页"},
            {"name": "Phase 3 流量护城河", "duration": "3-6 月", "action": "关键词护城河建立 + 自相竞争消除 + 跨词协同", "roi": "自然流量超越广告流量"},
        ],
        "layers": [
            {"no": "L1", "name": "数据采集层", "desc": "搜索量代理数据 · 竞品 Listing 抓取 · SP-API 搜索词报告"},
            {"no": "L2", "name": "关键词分析层", "desc": "蓝海缺口矩阵 · TF-IDF 竞品词挖掘 · 自相竞争检测"},
            {"no": "L3", "name": "Listing 优化层", "desc": "语义相关性评分 · 关键词密度控制 · 多语言生成"},
            {"no": "L4", "name": "排名追踪层", "desc": "位置弹性建模 · CTR/CVR 归因 · 排名因子 SHAP 分析"},
            {"no": "L5", "name": "广告协同层", "desc": "有机+付费协同预算 · 飞轮溢出 ROI 追踪 · ACoS 优化"},
            {"no": "L6", "name": "护城河层", "desc": "高域名词独占策略 · 竞品词反防御 · 品牌词保护"},
        ],
        "traps": [
            {"no": "①", "title": "只优化主词忽略长尾", "desc": "主词竞争激烈且排名见效慢（3-6个月）。长尾词（3-4词组合）竞争低且能立即带来转化流量。最优策略是80%精力投长尾、20%投主词，而非反过来。"},
            {"no": "②", "title": "用广告 ACOS 衡量广告对排名的贡献", "desc": "广告最大价值不是直接 ROAS，而是通过销量速度提升自然排名（飞轮效应）。必须同时追踪「广告期间自然排名变化」，否则会因为短期 ACOS 高而错误砍掉高价值广告词。"},
            {"no": "③", "title": "多 SKU 全部争同一组关键词", "desc": "同店 SKU 自相竞争会导致两个 Listing 互相压低对方排名，平台算法也会困惑。必须先做关键词自相竞争检测，然后为每个 SKU 分配专属关键词矩阵。"},
        ],
        "core_skills": [
            "Skill-Keyword-Demand-Gap-Analysis", "Skill-Amazon-Search-Ranking-Factor-Model",
            "Skill-Listing-Semantic-Relevance-Scoring", "Skill-Search-Position-Click-Elasticity",
            "Skill-Keyword-Cannibalization-Detection", "Skill-Organic-Paid-Rank-Synergy-Model",
            "Skill-Search-Tag-Keyword-Auto-Mapping", "Skill-Search-Ad-Budget-ROI-Integration",
            "Skill-LLM-Search-Query-Expansion", "Skill-Search-VOC-Signal-Loop",
            "Skill-Multilingual-Listing-Generation", "Skill-Combo-New-Product-Launch-Playbook",
        ],
    },
    {
        "id": "sol-voc-product-selection",
        "title": "VOC 情报 → 选品决策全链路架构",
        "subtitle": "用户声音驱动的母婴新品筛选与需求验证系统",
        "category": "选品增长 AI",
        "tags": ["VOC分析", "情感分析", "选品决策", "需求预测", "NLP"],
        "icon": "VP",
        "icon_color": "#10b981",
        "status": "published",
        "updated": "2026-06-21",
        "summary": "系统整合 Amazon 评论、Reddit 社交讨论、品牌差评三层 VOC 数据，通过情感分析、痛点聚类、需求强度评分，将用户真实声音转化为可量化的选品决策信号，输出 GO/NO-GO 推荐和首批 SKU 配置建议。",
        "roi_headline": "新品首月滞销率降低 35%，选品决策周期从 4 周压缩到 3 天",
        "phases": [
            {"name": "Phase 1 信号采集", "duration": "1-2 周", "action": "三层 VOC 数据接入（评论/社交/差评）", "roi": "覆盖 90% 消费者真实反馈"},
            {"name": "Phase 2 痛点挖掘", "duration": "2-4 周", "action": "情感分析 + 主题聚类 + 频次评分", "roi": "痛点识别准确率 >85%"},
            {"name": "Phase 3 机会评分", "duration": "1-2 月", "action": "需求强度 × 竞争密度 = 机会得分", "roi": "选品命中率提升 40%"},
            {"name": "Phase 4 需求预测", "duration": "2-3 月", "action": "时序 + VOC 情绪信号融合预测", "roi": "新品首季备货准确率 ±15%"},
        ],
        "layers": [
            {"no": "L1", "name": "数据采集层", "desc": "Amazon 评论爬取 · Reddit/X 社交 VOC · 品牌官网差评 · 异步去重队列"},
            {"no": "L2", "name": "NLP 处理层", "desc": "多语言情感分析 · ABSA 属性级情感 · BERTopic 主题聚类 · 事件框架提取"},
            {"no": "L3", "name": "信号量化层", "desc": "痛点频次 × 情感强度 = 信号热度 · 竞争密度指数 · VOC 趋势斜率"},
            {"no": "L4", "name": "决策推理层", "desc": "机会评分矩阵 · GO/NO-GO 阈值 · 首批 SKU 配置建议 · 三轨合规验证"},
        ],
        "core_skills": [
            "Skill-VOC-Proxy-NPS-AIPL-统一萃取引擎",
            "Skill-BERT-SRL-Event-Frame-Extraction",
            "Skill-Semantic-Blueprint-Compiler",
            "Skill-New-Product-Opportunity-Mining",
            "Skill-Product-Opportunity-Scoring",
            "Skill-Bass-Diffusion-New-Product-Forecasting",
            "Skill-Cross-Border-Cold-Start-Forecast",
            "Skill-Review-Dedup-Quality-Filter",
            "Skill-Fake-Review-Detection",
            "Skill-LLM-Focused-Web-Crawling",
        ],
        "traps": [
            {"no": "T1", "title": "VOC 滞后陷阱", "desc": "评论反映的是 3-6 个月前的需求，需结合搜索趋势做前向校正，避免追逐过时痛点上新"},
            {"no": "T2", "title": "样本偏差陷阱", "desc": "差评用户只占 5-10%，情感分布需加权，避免过度优化低频极端痛点而忽略沉默大多数"},
            {"no": "T3", "title": "语言墙陷阱", "desc": "多市场 VOC 需语种对齐后聚类，直接合并英/德/日评论会稀释核心信号，导致选品偏向英语市场"},
        ],
    },
    {
        "id": "sol-ads-organic-synergy",
        "title": "广告-自然流量协同增长架构",
        "subtitle": "搜索广告与自然排名一体化运营的 AI 决策系统",
        "category": "流量增长 AI",
        "tags": ["搜索广告", "自然排名", "ROAS优化", "关键词矩阵", "流量协同"],
        "icon": "AO",
        "icon_color": "#f59e0b",
        "status": "published",
        "updated": "2026-06-21",
        "summary": "打破广告投放与自然 SEO 分开管理的孤岛思维，构建关键词维度的「广告-自然」双轨监控体系。以自然排名位置为决策变量动态调整广告出价，在目标词自然排名提升期间逐步降低广告 ACoS，最终实现流量成本最优化。",
        "roi_headline": "综合 ACoS 降低 20-28%，自然流量占比从 35% 提升至 55%",
        "phases": [
            {"name": "Phase 1 关键词矩阵", "duration": "1-2 周", "action": "目标词分层（核心/长尾/防守）+ SOV 基线", "roi": "流量图谱可见化"},
            {"name": "Phase 2 双轨监控", "duration": "2-4 周", "action": "每日自然排名 + 广告位置 + 出价联动看板", "roi": "响应时延从周→天"},
            {"name": "Phase 3 协同出价", "duration": "1-2 月", "action": "自然排名↑→广告出价梯度下调算法", "roi": "ACoS 降低 15-20%"},
            {"name": "Phase 4 预算智能分配", "duration": "2-3 月", "action": "ROAS 预测 + 多目标预算分配优化器", "roi": "综合 ROAS 提升 30%"},
        ],
        "layers": [
            {"no": "L1", "name": "数据采集层", "desc": "自然排名快照（每日）· 广告位置 & 出价 · 搜索量趋势 · CVR/CTR 历史"},
            {"no": "L2", "name": "关键词分层层", "desc": "核心词（Top 20）· 长尾词矩阵 · 品牌防守词 · 竞品拦截词 · SOV 计算"},
            {"no": "L3", "name": "协同决策层", "desc": "自然位置→广告出价映射函数 · 季节性调节 · 竞品动作响应 · 置信区间门控"},
            {"no": "L4", "name": "预算优化层", "desc": "ROAS 预测模型 · 多目标线性规划 · 广告组预算再分配 · 归因窗口协调"},
        ],
        "core_skills": [
            "Skill-Amazon-Search-Ranking-Factor-Model",
            "Skill-Search-Share-of-Voice",
            "Skill-Search-Funnel-Attribution",
            "Skill-Brand-Defense-Search-Strategy",
            "Skill-Organic-Paid-Rank-Synergy-Model",
            "Skill-ROAS-Budget-Optimization",
            "Skill-Ad-Attribution-Modeling",
            "Skill-Search-Conversion-Rate-Predictor",
            "Skill-Hierarchical-Search-Intent-Classification",
            "Skill-Negative-Keyword-Safe-Guard",
        ],
        "traps": [
            {"no": "T1", "title": "归因冲突陷阱", "desc": "广告和自然同时出现时，Last-click 会把转化归给广告，导致自然流量价值被低估 40-60%，需用 Data-Driven Attribution 修正"},
            {"no": "T2", "title": "出价下调时机陷阱", "desc": "自然排名第 1 页不等于稳定，需连续 14 天 ≥ 第 5 位才可降广告出价，否则排名反弹后广告冷启动代价高"},
            {"no": "T3", "title": "关键词蚕食陷阱", "desc": "广告词与自然词高度重叠时，同一词内部竞价抬高 CPC，需用 Keyword Cannibalization Detection 提前分离广告与自然词池"},
        ],
    },
    {
        "id": "sol-inventory-risk-management",
        "title": "库存风险量化 → 智能补货决策架构",
        "subtitle": "从CVaR金融风险度量到多SKU库存组合的最优决策系统",
        "category": "供应链 AI",
        "tags": ["库存优化", "风险度量", "CVaR", "补货决策", "供应链韧性"],
        "icon": "IR",
        "icon_color": "#ef4444",
        "status": "published",
        "updated": "2026-06-21",
        "summary": "将金融风险管理的CVaR（期望损失）框架迁移到多SKU库存组合管理，量化「极端滞销场景」下的尾部风险。结合供应链网络的中介中心性分析识别瓶颈节点，构建从风险感知→安全库存动态调整→韧性补货决策的完整链路。",
        "roi_headline": "库存滞销率降低6-8%，极端断货损失降低40%，年化释放现金40-80万元",
        "phases": [
            {"name": "Phase 1 风险基线", "duration": "1-2周", "action": "CVaR库存风险建模+多SKU相关性矩阵", "roi": "量化尾部风险，告别直觉备货"},
            {"name": "Phase 2 韧性诊断", "duration": "2-4周", "action": "供应链网络中介中心性+瓶颈识别", "roi": "关键供应商断货预警提前30天"},
            {"name": "Phase 3 动态决策", "duration": "1-2月", "action": "P95触发安全库存自动调整+补货执行", "roi": "断货率降低25%"},
            {"name": "Phase 4 闭环优化", "duration": "持续", "action": "大促CVaR压测+备货方案自动生成", "roi": "大促备货准确率+15%"},
        ],
        "layers": [
            {"no": "L1", "name": "风险感知层", "desc": "多SKU历史需求数据 · 前置期分布建模 · 季节性分解"},
            {"no": "L2", "name": "CVaR量化层", "desc": "Monte Carlo需求模拟 · 组合CVaR计算 · 边际风险贡献"},
            {"no": "L3", "name": "网络韧性层", "desc": "供应链有向图 · 中介中心性 · 瓶颈节点识别 · 断供影响模拟"},
            {"no": "L4", "name": "决策执行层", "desc": "安全库存动态公式 · P95触发补货 · 资金约束优化 · 执行回路"},
        ],
        "core_skills": [
            "Skill-CVaR-Inventory-Risk-Portfolio",
            "Skill-Supply-Chain-Network-Betweenness-Resilience",
            "Skill-Lead-Time-Safety-Stock-Auto-Adjuster",
            "Skill-Lead-Time-Distribution-Risk-GenQOT",
            "Skill-Multi-Echelon-Inventory",
            "Skill-Safety-Stock-Replenishment",
            "Skill-Demand-Forecasting-Supply-Chain",
            "Skill-Conformal-Prediction-Demand-UQ",
            "Skill-Markdown-Clearance-Auto-Trigger",
            "Skill-MAS-Multi-Warehouse-Replenishment-Consensus",
        ],
        "traps": [
            {"no": "T1", "title": "CVaR参数估计陷阱", "desc": "历史数据不足时（<24个月），CVaR会严重低估极端风险。必须用Bootstrap重采样+情景模拟扩增样本"},
            {"no": "T2", "title": "相关性崩溃陷阱", "desc": "大促期间SKU相关性显著升高（全线爆单），平时的相关矩阵在大促时失效，需单独建大促情景模型"},
            {"no": "T3", "title": "网络拓扑过时陷阱", "desc": "供应链网络中介中心性每季度重算一次，供应商变动后必须更新，否则韧性评估失真"},
        ],
    },
    {
        "id": "sol-viral-growth-engine",
        "title": "病毒传播预测 → 爆品增长引擎架构",
        "subtitle": "SIR流行病学 + VOC信号 + 内容工厂的爆品全链路增长系统",
        "category": "增长 AI",
        "tags": ["SIR模型", "病毒传播", "TikTok", "VOC", "爆品预测", "增长引擎"],
        "icon": "VG",
        "icon_color": "#8b5cf6",
        "status": "published",
        "updated": "2026-06-21",
        "summary": "将流行病学SIR模型迁移到TikTok短视频爆品传播预测，通过发布后72小时的早期信号拟合传播参数R₀，预测需求峰值时间和量级。结合VOC信号环路识别「有病毒传播潜力」的产品特征，构建从内容发布→传播预测→备货响应→库存执行的完整增长引擎。",
        "roi_headline": "爆单备货准确率提升35%，断货损失年化减少50万元，爆品发现周期从4周→72小时",
        "phases": [
            {"name": "Phase 1 信号捕获", "duration": "持续监控", "action": "TikTok/社媒UGC病毒潜力评分+VOC早期信号提取", "roi": "爆品识别提前4周"},
            {"name": "Phase 2 传播预测", "duration": "发布后72h", "action": "SIR参数拟合+R₀计算+需求峰值预测", "roi": "峰值时间预测误差<2天"},
            {"name": "Phase 3 备货响应", "duration": "发布后7天", "action": "需求曲线→补货量计算→紧急补货触发", "roi": "断货率降低50%"},
            {"name": "Phase 4 内容迭代", "duration": "持续", "action": "差评信号→产品改进→新内容测试→传播扩大", "roi": "产品迭代周期缩短60%"},
        ],
        "layers": [
            {"no": "L1", "name": "信号采集层", "desc": "TikTok观看/点赞/转发数据 · UGC晒单识别 · VOC评论流式采集"},
            {"no": "L2", "name": "传播建模层", "desc": "SIR微分方程求解 · β/γ参数拟合 · R₀计算 · 置信区间构建"},
            {"no": "L3", "name": "需求预测层", "desc": "传播曲线→需求曲线映射 · 市场规模约束 · 季节性叠加"},
            {"no": "L4", "name": "增长执行层", "desc": "需求峰值触发补货 · 内容放大决策 · VOC反馈迭代 · 增长闭环"},
        ],
        "core_skills": [
            "Skill-SIR-Viral-Product-Adoption-Forecasting",
            "Skill-UGC-Viral-Content-Potential-Scorer",
            "Skill-VOC-Churn-Early-Warning-Signal",
            "Skill-VOC-Product-Iteration-Signal-Extractor",
            "Skill-Review-Driven-Growth-Opportunity-Scorer",
            "Skill-Bass-Diffusion-New-Product-Forecasting",
            "Skill-TikTok-Shop-Content-Attribution",
            "Skill-Seasonal-Search-Trend-Modeling",
            "Skill-Content-ROI-Budget-Shift-Trigger",
            "Skill-Demand-Forecasting-Supply-Chain",
        ],
        "traps": [
            {"no": "T1", "title": "R₀过拟合陷阱", "desc": "72小时早期数据量太少，β/γ估计方差极大。必须设置R₀上限（如R₀<5）和下限（>0.1），防止离群点驱动的过拟合"},
            {"no": "T2", "title": "传播饱和陷阱", "desc": "SIR模型假设人群均匀混合，但TikTok算法推送会造成「二次传播」，导致实际需求出现双峰。需在模型中加入推送放大因子"},
            {"no": "T3", "title": "库存响应延迟陷阱", "desc": "传播峰值预测再准，如果供应链前置期是30天，仍然赶不上3天后的需求峰。爆品备货的核心是「预测触发补货」要早于传播信号出现"},
        ],
    },
    {
        "id": "sol-cdp-lookalike-full-stack",
        "title": "CDP 全链路：身份统一 → 种子净化 → Lookalike 扩展",
        "subtitle": "从碎片化多平台数据到高质量广告受众的完整架构",
        "category": "CDP & 广告技术",
        "tags": ["CDP", "Lookalike", "身份统一", "广告投放", "隐私合规"],
        "icon": "CDP",
        "icon_color": "#0ea5e9",
        "status": "published",
        "updated": "2026-06-24",
        "summary": "解决母婴跨境卖家最核心的数据碎片化问题：Amazon/TikTok/独立站同一用户三套 ID，导致 Lookalike 种子质量差、广告重复触达、归因失真。三层 CDP 架构彻底打通，ROAS 从 1.9x 恢复到 3.5x+。",
        "roi_headline": "广告 ROAS 提升 40-80%，年化增效 20-40 万元，GDPR 合规零风险",
        "phases": [
            {"name": "Phase 1 身份统一", "duration": "2-3 周", "action": "L1 哈希匹配 + L2 行为概率 + L3 图结构", "roi": "跨平台识别率 85%+"},
            {"name": "Phase 2 种子净化", "duration": "1 周", "action": "孤立森林 + 代理分类器剔除刷单/员工内购", "roi": "种子纯度 68%→94%"},
            {"name": "Phase 3 Lookalike 扩展", "duration": "2 周", "action": "双塔 / 图传播 / 联邦 Lookalike 三路并行", "roi": "ROAS 提升 40-80%"},
            {"name": "Phase 4 置信校准", "duration": "1 周", "action": "Platt Scaling + Precision@K 决策扩展比例", "roi": "避免盲目扩量损失"},
        ],
        "layers": [
            {"no": "L1", "name": "身份统一层", "desc": "哈希匹配 + 行为概率匹配 + GNN 跨设备匹配 → 统一 CDP 用户 ID"},
            {"no": "L2", "name": "种子质量层", "desc": "规则过滤 + 孤立森林异常检测 + 代理分类器净化"},
            {"no": "L3", "name": "Lookalike 建模层", "desc": "双塔自建 / 图神经网络传播 / 联邦学习（隐私合规）"},
            {"no": "L4", "name": "置信度校准层", "desc": "密度估计 + Platt Scaling + Precision@K 扩展决策"},
        ],
        "traps": [
            {"no": "①", "title": "跳过种子净化直接建模", "desc": "含 10-30% 噪声种子的 Lookalike 模型 ROAS 可能低于随机投放。种子净化是 Lookalike 效果的天花板，不是可选优化。"},
            {"no": "②", "title": "盲目扩展到 10% 受众", "desc": "未校准的 Lookalike 分数在 Top 5%→10% 时精度骤降。必须用 Platt Scaling 校准后再决定扩展比例，否则 ROAS 崩盘。"},
            {"no": "③", "title": "欧盟市场直接上传用户哈希", "desc": "GDPR Article 9 对儿童数据有特殊保护。欧盟市场必须用联邦 Lookalike 方案，数据不出本地。"},
        ],
        "core_skills": [
            "Skill-Multi-Source-User-Identity-Unification",
            "Skill-Seed-Quality-Optimization-for-Lookalike",
            "Skill-Dual-Tower-Lookalike-Modeling",
            "Skill-Graph-Neural-Lookalike-Propagation",
            "Skill-Privacy-Preserving-Lookalike-FL",
            "Skill-Calibrated-Audience-Expansion-Uncertainty",
            "Skill-Cleanroom-Audience-Collaboration",
            "Skill-Tag-Driven-Ad-Audience-Segmentation",
        ],
    },
    {
        "id": "sol-member-growth-system",
        "title": "会员增长体系：等级设计 → 生命周期干预 → 裂变归因",
        "subtitle": "从零搭建母婴跨境 DTC 完整会员运营闭环",
        "category": "会员运营 AI",
        "tags": ["会员体系", "LTV", "生命周期", "裂变", "积分管理"],
        "icon": "MEM",
        "icon_color": "#8b5cf6",
        "status": "published",
        "updated": "2026-06-24",
        "summary": "为母婴 DTC 品牌提供从等级体系设计到运营执行的完整 AI 方案。Markov CLV 优化等级门槛，RL 序列干预精准触达，裂变网络价值精算激励额度，积分负债精算控制财务风险。",
        "roi_headline": "会员 CLV 提升 15-25%，干预成本降低 30%，年化增收 50-150 万元",
        "phases": [
            {"name": "Phase 1 体系设计", "duration": "1-2 周", "action": "Markov CLV 优化等级结构 + 门槛", "roi": "CLV +12-18%"},
            {"name": "Phase 2 注册优化", "duration": "2 周", "action": "分市场漏斗 + 早期 LTV 预测动态激励", "roi": "注册转化 +10-15pp"},
            {"name": "Phase 3 生命周期运营", "duration": "持续", "action": "RL 序列干预 + 图预警 + 积分精算", "roi": "流失率 -20%"},
            {"name": "Phase 4 裂变扩增", "duration": "持续", "action": "裂变价值精算 + 分层激励 + 超级推荐者", "roi": "获客成本 -40%"},
        ],
        "layers": [
            {"no": "L1", "name": "体系设计层", "desc": "Markov 链 CLV 建模 → 最优等级数量和门槛 → 积分负债精算"},
            {"no": "L2", "name": "获客转化层", "desc": "跨境注册漏斗分市场优化 → 早期 LTV 预测 → 动态激励分配"},
            {"no": "L3", "name": "生命周期管理层", "desc": "RL 序列干预 → 图神经网络流失预警 → 会员阶段触达策略"},
            {"no": "L4", "name": "裂变扩增层", "desc": "裂变网络价值归因 → 最优激励额度 → 超级推荐者识别与激励"},
        ],
        "traps": [
            {"no": "①", "title": "等级门槛拍脑袋设定", "desc": "三级门槛 $50/$200/$500 是最常见的随意设定。Markov CLV 优化后，最优门槛可能完全不同（如 $80/$300），且不同用户类型最优门槛不同。"},
            {"no": "②", "title": "所有用户同一干预策略", "desc": "给高意图用户发 25% 折扣券是浪费。RL 序列干预证明：高意图用户只需内容触达，低意图用户才需折扣。统一策略比个性化策略多花 30-40%。"},
            {"no": "③", "title": "积分体系越来越成功越亏损", "desc": "积分发放量快速增长但兑换率被低估，积分负债在资产负债表上悄悄累积。必须用 Beta-Binomial 精算兑换率，季度审查积分负债。"},
        ],
        "core_skills": [
            "Skill-Membership-Tier-Design-Optimization",
            "Skill-Cross-Border-Member-Onboarding-Optimization",
            "Skill-Member-Lifecycle-Intervention-Sequencing",
            "Skill-Membership-Churn-Early-Warning-Graph",
            "Skill-Points-Expiry-Redemption-Liability-Model",
            "Skill-Referral-Network-Value-Attribution",
            "Skill-Loyalty-Program-ROI-Modeling",
            "Skill-LTV-Prediction-ZILN",
        ],
    },
    {
        "id": "sol-privacy-safe-advertising",
        "title": "隐私合规广告架构：联邦 Lookalike + 洁净室 + 因果去偏",
        "subtitle": "Cookie 消亡时代的跨境广告精准投放全栈解决方案",
        "category": "隐私合规 & 广告技术",
        "tags": ["隐私合规", "GDPR", "联邦学习", "归因去偏", "洁净室"],
        "icon": "PPA",
        "icon_color": "#10b981",
        "status": "published",
        "updated": "2026-06-24",
        "summary": "GDPR/CCPA/PIPL 三法叠加的合规压力下，传统广告方法论正在失效。本方案提供「数据不出境 + 归因不失真 + 受众不泄露」的完整技术栈，在最严苛的隐私约束下维持广告效果。",
        "roi_headline": "欧盟/北美市场广告合规零风险，ROAS 提升 12-20%，规避最高 4% 全球营收罚款",
        "phases": [
            {"name": "Phase 1 合规评估", "duration": "1 周", "action": "数据流审计 + GDPR 风险识别 + 优先级排序", "roi": "消除法律盲区"},
            {"name": "Phase 2 联邦 Lookalike", "duration": "4-6 周", "action": "VFL 跨平台建模，原始数据不出本地", "roi": "Lookalike 质量 +12%"},
            {"name": "Phase 3 洁净室协作", "duration": "2-3 周", "action": "AWS Clean Rooms 受众重叠分析 + 媒体规划", "roi": "媒体决策准确率 +30%"},
            {"name": "Phase 4 归因去偏", "duration": "2 周", "action": "IPW 去混淆，识别真实 iROAS", "roi": "避免预算浪费 15-20 万"},
        ],
        "layers": [
            {"no": "L1", "name": "身份隐私层", "desc": "哈希 ID 匹配 + 差分隐私保护 + K-匿名性约束"},
            {"no": "L2", "name": "联邦建模层", "desc": "垂直联邦学习 VFL + 知识蒸馏 + 非对齐用户处理"},
            {"no": "L3", "name": "洁净室协作层", "desc": "AWS Clean Rooms / 自建 DCR + SQL 受众分析"},
            {"no": "L4", "name": "因果归因层", "desc": "IPW 倒数概率加权 + 混淆去偏 + 真实 iROAS 计算"},
        ],
        "traps": [
            {"no": "①", "title": "用哈希邮箱上传就认为合规", "desc": "SHA-256 哈希可被逆向工程还原，且 GDPR 明确规定哈希数据仍属个人数据。欧盟市场必须用联邦学习，禁止任何形式的用户数据上传。"},
            {"no": "②", "title": "相信平台报告的 ROAS", "desc": "平台 ROAS 通常高估 25-45%（混淆偏差）。按高估 ROAS 加大预算，实际是在「高意图人群」上浪费广告费。必须用 IPW 计算真实 iROAS 再做预算决策。"},
            {"no": "③", "title": "洁净室查询没有 K-匿名性约束", "desc": "分组数量 < 50 的洁净室查询结果可反向推断个人信息。必须设置最小分组阈值，否则洁净室成为隐私泄露渠道。"},
        ],
        "core_skills": [
            "Skill-Privacy-Preserving-Lookalike-FL",
            "Skill-Cleanroom-Audience-Collaboration",
            "Skill-Counterfactual-Ad-Attribution-Debiasing",
            "Skill-CDA-Privacy-Causal-Attribution",
            "Skill-Privacy-Safe-Identity-Resolution",
            "Skill-Ad-Creative-Personalization-Bandit",
            "Skill-Constrained-Multi-Objective-Ad-Delivery",
            "Skill-Cross-Channel-Budget-Pacing-Controller",
        ],
    },

    {
        "id": "sol-causal-intelligence-pricing",
        "title": "因果智能定价体系",
        "subtitle": "DML去偏弹性 × 异质用户定价 × 市场准入评估",
        "category": "定价策略 AI",
        "tags": ["因果推断", "价格弹性", "DML", "X-Learner", "合成控制"],
        "icon": "CI",
        "icon_color": "#7c3aed",
        "status": "published",
        "updated": "2026-07",
        "summary": "传统OLS价格弹性估计因季节/促销混淆存在50%+偏差——甚至出现错误方向。本方案用双重去偏机器学习(DML)获得无偏弹性，X-Learner识别异质用户群差异，合成控制法评估新市场准入ROI，形成因果驱动的完整定价决策体系。",
        "roi_headline": "弹性估计偏差1.57→0.12，年化定价优化GMV约120万元",
        "phases": [
            {"name": "Phase 1 弹性重建", "duration": "2-3周", "action": "DML去偏弹性估计替换OLS", "roi": "定价偏差归零"},
            {"name": "Phase 2 人群差异化", "duration": "4-6周", "action": "X-Learner异质弹性，用券替代全量降价", "roi": "节省40%券成本"},
            {"name": "Phase 3 市场评估", "duration": "2-3月", "action": "ASCM评估新市场准入效果", "roi": "年化减少错误扩张损失80万"},
        ],
        "layers": [
            {"no": "L1", "name": "去偏弹性层", "desc": "DML双重去偏，控制季节/促销混淆变量，获得真实价格因果效应"},
            {"no": "L2", "name": "异质效应层", "desc": "X-Learner识别不同月龄段/消费层级用户的弹性差异，精准发券"},
            {"no": "L3", "name": "市场评估层", "desc": "Augmented Synthetic Control评估新市场准入，合成对照组消除自然趋势"},
            {"no": "L4", "name": "因果时序层", "desc": "CausalImpact量化促销活动的真实增量，识别需求借贷vs真实增长"},
        ],
        "traps": [
            {"no": "①", "title": "用OLS估计弹性直接指导降价", "desc": "季节效应+促销混淆导致OLS弹性偏差50%以上，用-0.3的弹性做降价决策可能亏损。必须先用DML去偏。"},
            {"no": "②", "title": "全量降价而非精准发券", "desc": "弹性分析显示老用户弹性-0.6（不敏感），新用户弹性-2.1（高敏感）。全量降价损失高弹性用户外的利润。"},
            {"no": "③", "title": "不做安慰剂检验直接上合成控制", "desc": "ASCM有效性依赖捐赠市场的平行趋势假设，必须做安慰剂检验和敏感性分析验证结论可信度。"},
        ],
        "core_skills": [
            "Skill-Double-Debiased-ML-Price",
            "Skill-Heterogeneous-Treatment-Effect-XLearner",
            "Skill-Augmented-Synthetic-Control-ML",
            "Skill-Causal-Time-Series-CausalImpact",
            "Skill-RDD-Regression-Discontinuity-Design",
            "Skill-Propensity-Score-Matching-QuasiExp",
            "Skill-IV-Instrumental-Variables",
            "Skill-Causal-Representation-Learning",
        ],
    },
    {
        "id": "sol-video-commerce-intelligence",
        "title": "视频电商全链路智能化",
        "subtitle": "MAS自动内容 × 商品标签化 × 因果ROI归因",
        "category": "内容营销 AI",
        "tags": ["视频电商", "MAS", "TikTok", "RLHF", "因果归因"],
        "icon": "VC",
        "icon_color": "#ec4899",
        "status": "published",
        "updated": "2026-07",
        "summary": "视频电商面临三大痛点：内容产量不足（手工3h/篇）、商品关联率低（人工打标错误15%）、ROI归因不清（平台报告高估30%）。本方案用MAS多智能体自动化内容生产，多模态LLM实现视频商品标签化，Geo实验+因果方法获得真实增量ROI。",
        "roi_headline": "爆款率5%→18%，年化GMV增量约150万元，内容成本降低97%",
        "phases": [
            {"name": "Phase 1 内容自动化", "duration": "2-4周", "action": "MAS部署+AIGC内容矩阵", "roi": "内容量1→3篇/天"},
            {"name": "Phase 2 商品标签化", "duration": "3-5周", "action": "多模态LLM视频商品识别", "roi": "打标准确率88%，节省75%人工"},
            {"name": "Phase 3 因果归因", "duration": "6-8周", "action": "Geo实验揭示平台归因偏差", "roi": "年化节省40万元无效广告"},
        ],
        "layers": [
            {"no": "L1", "name": "内容生产层", "desc": "Trend Agent选题→Script Agent脚本→Production Agent生成→Analytics Agent分析，3h→10min"},
            {"no": "L2", "name": "商品关联层", "desc": "CLIP多模态识别视频中商品，FAISS向量检索匹配SKU，自动生成购物链接"},
            {"no": "L3", "name": "质量对齐层", "desc": "RLHF奖励模型筛选高质量内容，从5个候选选最优，转化率+18%"},
            {"no": "L4", "name": "因果归因层", "desc": "Geo Holdout实验揭示平台归因虚高，获得真实增量ROI，优化预算分配"},
        ],
        "traps": [
            {"no": "①", "title": "直接用平台Last-Click归因评估视频ROI", "desc": "TikTok平台归因通常高估真实增量30%（最后点击≠真实原因）。必须做Geo Holdout实验获得真实增量。"},
            {"no": "②", "title": "内容标签化后忽略质量控制", "desc": "LLM识别准确率88%≠100%，12%的错误关联会导致买家投诉。必须设置置信度阈值和人工抽检机制。"},
            {"no": "③", "title": "MAS系统没有安全护栏", "desc": "自动生成的内容可能包含误导性医疗建议（母婴场景高风险）。必须在发布前加入LLM-as-Judge质检步骤。"},
        ],
        "core_skills": [
            "Skill-MAS-Video-Content-Optimization",
            "Skill-Tag-Video-Commerce-Tagging",
            "Skill-Reward-Model-RLHF-Ecommerce",
            "Skill-AI-Content-Marketing-Growth",
            "Skill-Geo-Holdout-Experiment",
            "Skill-DataAgent-Marketing-Attribution",
            "Skill-Causal-Time-Series-CausalImpact",
            "Skill-LLM-as-Judge-Evaluator",
        ],
    },
    {
        "id": "sol-logistics-intelligence-esg",
        "title": "物流智能化2.0 × ESG合规",
        "subtitle": "动态路由 × 冷链合规 × 碳足迹优化 × 智能承运商选择",
        "category": "物流履约 AI",
        "tags": ["物流智能化", "冷链", "ESG", "碳排放", "动态路由"],
        "icon": "LI",
        "icon_color": "#10b981",
        "status": "published",
        "updated": "2026-07",
        "summary": "2025-2026年欧盟CBAM和ESG信披要求使跨境物流从纯成本问题升级为合规+效率+可持续的三维挑战。本方案提供从冷链FDA合规到碳排放优化再到ML智能承运商选择的完整物流智能化升级路径。",
        "roi_headline": "冷链FDA通关率85%→98%，物流成本降低8%，年化综合ROI约245万元",
        "phases": [
            {"name": "Phase 1 合规基础", "duration": "2-3周", "action": "冷链IoT监测+碳足迹核算", "roi": "FDA通关率提升"},
            {"name": "Phase 2 成本优化", "duration": "4-6周", "action": "ML承运商选择+碳最优路径", "roi": "物流成本降低8%"},
            {"name": "Phase 3 实时智能", "duration": "2-3月", "action": "动态重路由+知识图谱决策", "roi": "实时响应突发事件"},
        ],
        "layers": [
            {"no": "L1", "name": "合规监控层", "desc": "IoT冷链温控全程监测，MKT计算，自动生成FDA/EU合规报告"},
            {"no": "L2", "name": "碳足迹层", "desc": "GHG Protocol碳排放计算，ESG报告自动化，CBAM碳税合规"},
            {"no": "L3", "name": "承运商优化层", "desc": "ML多目标承运商选择，帕累托最优成本-时效-碳排放组合"},
            {"no": "L4", "name": "实时路由层", "desc": "事件驱动动态重路由，突发堵塞/故障的实时路径重规划"},
            {"no": "L5", "name": "知识图谱层", "desc": "物流KG统一认证/关税/航线知识，3秒完成跨境发货决策查询"},
        ],
        "traps": [
            {"no": "①", "title": "用历史平均温度代替MKT评估冷链合规", "desc": "FDA要求使用Mean Kinetic Temperature(MKT)而非简单平均，直接平均会低估热暴露风险，导致合规报告被拒。"},
            {"no": "②", "title": "只计算运输排放忽略仓储和包装", "desc": "GHG Protocol Scope 3要求完整供应链碳足迹，仅计算运输可能遗漏40%以上的碳排放，导致CSRD报告不合规。"},
            {"no": "③", "title": "动态重路由没有司机接受机制", "desc": "欧洲劳工法规要求给司机提供拒绝临时路线调整的选项，强制自动调度可能引发法律纠纷。"},
        ],
        "core_skills": [
            "Skill-Cold-Chain-Temperature-Monitoring",
            "Skill-Green-Logistics-Carbon-Optimization",
            "Skill-Carbon-Footprint-ML-Model",
            "Skill-Carrier-Selection-ML",
            "Skill-Real-Time-Fleet-Dynamic-Routing",
            "Skill-KG-Logistics-Intelligence",
            "Skill-Drone-UAV-Last-Mile-Delivery",
            "Skill-User-Analytics-Logistics-Bridge",
        ],
    },
    {
        "id": "sol-ai-engineering-acceleration",
        "title": "AI工程效率加速体系",
        "subtitle": "推理加速 × 主动检索 × 少样本学习 × 持续学习",
        "category": "AI工程 基础设施",
        "tags": ["推理加速", "Agentic RAG", "ICL", "持续学习", "KV-Cache"],
        "icon": "AE",
        "icon_color": "#f59e0b",
        "status": "published",
        "updated": "2026-07",
        "summary": "随着AI Agent系统规模扩大，工程效率成为核心瓶颈：推理延迟高（Agent每次8秒）、RAG噪声多（固定检索准确率85%）、新品类无训练数据（少样本困境）、模型季节退化（无持续学习）。本方案提供4个维度的AI工程效率提升路径。",
        "roi_headline": "Agent延迟降低50-63%，年化GPU成本节省约45万元，客服准确率85%→95%",
        "phases": [
            {"name": "Phase 1 推理加速", "duration": "1-2周", "action": "vLLM+Speculative Decoding+KV-Cache", "roi": "延迟降低50%+"},
            {"name": "Phase 2 检索智能化", "duration": "2-4周", "action": "Self-RAG按需检索替换固定RAG", "roi": "准确率+10%，成本-40%"},
            {"name": "Phase 3 少样本部署", "duration": "1-2周", "action": "TabPFN ICL新品类即时建模", "roi": "新品类当天上线风控"},
            {"name": "Phase 4 持续学习", "duration": "4-6周", "action": "EWC持续学习防止模型退化", "roi": "季节MAPE稳定在<12%"},
        ],
        "layers": [
            {"no": "L1", "name": "推理加速层", "desc": "Speculative Decoding草稿模型+目标模型协作，KV-Cache Prefix Sharing共享System Prompt"},
            {"no": "L2", "name": "主动检索层", "desc": "Self-RAG按需触发检索，FLARE置信度驱动，比固定RAG减少40%冗余检索"},
            {"no": "L3", "name": "少样本层", "desc": "TabPFN ICL 1秒建模，新品类50条样本AUC从0.62→0.82，无需训练周期"},
            {"no": "L4", "name": "持续学习层", "desc": "EWC弹性权重约束，季节切换不遗忘旧知识，模型跨季节MAPE从28%降至11%"},
        ],
        "traps": [
            {"no": "①", "title": "投机解码草稿模型与目标模型架构差异过大", "desc": "草稿模型接受率<40%时投机解码反而更慢。必须用同家族模型（Llama-7B草稿→Llama-70B目标）并预测接受率。"},
            {"no": "②", "title": "直接用TabPFN处理>1000条样本的任务", "desc": "TabPFN在样本量>1000、特征>100时性能下降明显。必须先用样本量判断：<200→ICL，200-5k→TabPFN+XGB集成，>5k→传统ML。"},
            {"no": "③", "title": "EWC λ值设置过大冻结所有参数", "desc": "λ过大使模型完全无法学习新知识，λ过小遗忘旧知识。必须在验证集上调优λ，目标是新旧任务的性能均衡。"},
        ],
        "core_skills": [
            "Skill-Speculative-Decoding-Agent",
            "Skill-KV-Cache-Optimization-Agent",
            "Skill-Agentic-RAG-Active-Retrieval",
            "Skill-In-Context-Learning-Tabular",
            "Skill-Continual-Learning-Production",
            "Skill-Reward-Model-RLHF-Ecommerce",
            "Skill-Multi-Task-Ad-CTR-CVR",
            "Skill-Synthetic-Data-Generation-Tabular",
        ],
    },
]



